#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  Copyright 2023 Abdelkrime Aries <kariminfo0@gmail.com>
#
#  ---- AUTHORS ----
# 2023	Abdelkrime Aries <kariminfo0@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys, getopt
import pandas as pd

import logging, os
logging.disable(logging.WARNING)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from jslML.preprocess.tools import prepare_data_char_bert
from jslML.models.en_word_emb import new_eng_char_bert, train_eng_char_bert
from jslML.preprocess.char_encoders import eng_char_encode

word_length = 14

def help():
    hlp = """char_emb_train [-i | --in] <file-name> [-o | --out] <file-name>:
    Read a list of files using URLs stored in the first file
        Then generate a CSV file containing the first word, the second, and if it is next
    """
    print(hlp)


def get_X_Y(url):
    df = pd.read_csv(url, sep=";", header=None)
    return prepare_data_char_bert(df, char_encoder=eng_char_encode, word_length=word_length)

def main(argv):
    try:
        opts, args = getopt.getopt(argv,"hi:o:",["help", "in=", "out="])
    except getopt.GetoptError:
        help()
        sys.exit(2)

    inURL = None
    outURL = None

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            help()
            sys.exit()
        elif opt in ("-i", "--in"):
            inURL = arg
        elif opt in ("-o", "--out"):
            outURL = arg

    if inURL is None:
        print("You have to specify a file as input")
        sys.exit()
    elif not os.path.isfile(inURL):
        print("The input file does not exist")
        sys.exit()
    if outURL is None:
        print("You have to specify a file as output")
        sys.exit()

    X, Y = get_X_Y(inURL)
    Y = np.array(Y).reshape(-1, 1)
    X = np.array(X)
    brt = new_eng_char_bert()
    train_eng_char_bert(brt, X, Y)

    tf.saved_model.save(brt, outURL)


if __name__ == "__main__":
    main(sys.argv[1:])